config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "home#index"
    get "signup", to: "users#new"
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    resources :categories, only: :show
    resources :users

    namespace :admin do 
      root "home#index"
      
      resources :categories
      resources :products
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  def self.options_for_select
    all.map do |category|
      [category.name, category.id]
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  validates :fullname, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  enum role: { user: 0, admin: 1 }
  has_secure_password
  # validates :password, presence: true, length: { minimum: 6 }

  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ActionController::Base
    include SessionsHelper

    layout "admin_application"

    before_action :check_admin

    def check_admin
      redirect_to root_path if current_user.blank? || current_user.user?
    end
  end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::AdminController
    before_action :set_category, only: %i[edit update destroy]
    
    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new params_category
      if @category.save
        redirect_to admin_categories_path
      else
        render :new
      end
    end

    def edit; end

    def update
      if @category.update params_category
        redirect_to admin_categories_path
      else
        render :index
      end
    end

    def destroy
      @category.destroy!
      redirect_to admin_categories_path
    end

    private

    def params_category
      params.require(:category).permit :name
    end

    def set_category
      @category = Category.find_by id: params[:id]
    end
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < Admin::AdminController
    def index; end
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::AdminController
    before_action :set_product, only: %i[edit update destroy]

    def index
      @products = Product.all
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new params_product
      if @product.save
        redirect_to admin_products_path
      else
        render :new
      end
    end

    def edit; end

    def update
      if @product.update params_product
        redirect_to admin_products_path
      else
        render :edit
      end
    end

    def destroy
      @product.destroy!
      redirect_to admin_products_path
    end

    private

    def params_product
      params.require(:product).permit :name, :price, :quantity, :category_id, :description, :image
    end

    def set_product
      @product = Product.find_by id: params[:id]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale, :set_category

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def set_category
    @categories = Category.all
  end

  include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @products = Product.where(category_id: params[:id])
    @categories = Category.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    return log_in_for(user) if user.present? && user.authenticate(params[:session][:password])

    flash.now[:danger] = "Invalid email/password combination"
    render "new"
  end

  def destroy
    log_out
    redirect_to root_path
  end

  def log_in_for(user)
    log_in user
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: %i[index new create]

  def new
    @user = User.new
  end

  def show; end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_path
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit :fullname, :email, :password, :password_confirmation
  end

  def set_user
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
  end
end

app/views/admin/categories/edit.html.erb
<%= form_for :category, url: admin_category_path, method: :patch do |f| %>
  <div class="row" style="justify-content: center;">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group">
        Name: <%= f.text_field :name %><br />
      </div>
      <div class="form-group">
        <%= f.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/categories/index.html.erb
<p>Danh sach bai Categories</p>

<%= link_to "<button class='btn btn-outline-success'>Create New</button>".html_safe, new_admin_category_path %>

<table style="border-collapse: collapse;">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Action</th>
	</tr>
  <% @categories.map do |cate| %>
		<tr>
			<td><%= cate.id %></td>
			<td><%= cate.name %></td>
			<td>
				<%= link_to "<button class='btn btn-outline-info'>Edit</button>".html_safe,  edit_admin_category_path(nil, cate) %>
				<%= link_to "<button class='btn btn-outline-danger'>Delete</button>".html_safe, admin_category_path(nil, cate), method: :delete %>	
			</td>
		</tr>
	<% end %>
</table>

app/views/admin/categories/new.html.erb
<%= form_for :category, url: admin_categories_path do |f| %>
  <div class="row" style="justify-content: center;">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group">
        Name: <%= f.text_field :name %><br/>
      </div>
      <div class="form-group">
        <%= f.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<%= form_for :product, url: admin_product_path, method: :patch do |f| %>
  <div class="row" style="justify-content: center;">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group">
        Name: <%= f.text_field :name, class: "form-control" %><br/>
      </div>
      <div class="form-group">
        Price: <%= f.text_field :price, class: "form-control" %><br/>
      </div>
      <div class="form-group">
        Quantity: <%= f.text_field :quantity, class: "form-control" %><br/>
      </div>
      <div class="form-group">
        Category:
        <%= f.select :category_id, Category.options_for_select, class: "form-control" %><br>
      </div>
      <div class="form-group">
        Description: <%= f.text_area :description, class: "form-control" %><br/>
      </div>
      <div class="form-group">
        Image: <%= f.text_field :image, class: "form-control" %><br/>
      </div>
      <div class="form-group">
        <%= f.submit %>
      </div>
<% end %>

app/views/admin/products/index.html.erb
<p>Danh sach product</p>

<%= link_to "<button class='btn btn-outline-success'>Product New</button>".html_safe, new_admin_product_path %>

<table style="border-collapse: collapse;">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Price</th>
		<th>Quantity</th>
		<th>Category</th>
		<th>Description</th>
		<th>Image</th>
		<th>Action</th>
	</tr>
  <% @products.map do |product| %>
		<tr>
			<td><%= product.id %></td>
			<td><%= product.name %></td>
			<td><%= product.price %></td>
			<td><%= product.quantity %></td>
			<td><%= product.category_id %></td>
			<td><%= product.description %></td>
			<td><%= product.image %></td>
			<td>
				<%= link_to "<button class='btn btn-outline-info'>Edit</button>".html_safe,  edit_admin_product_path(nil, product) %>
				<%= link_to "<button class='btn btn-outline-danger'>Delete</button>".html_safe, admin_product_path(nil, product), method: :delete %>	
			</td>
		</tr>
	<% end %>
</table>

app/views/admin/products/new.html.erb
<%= form_for :product, url: admin_products_path do |f| %>
<div class="row" style="justify-content: center;">
  <div class="col-md-6 col-md-offset-3">
    <div class="form-group">
      Name: <%= f.text_field :name, class: "form-control"%><br/>
    </div>
    <div class="form-group">
      Price: <%= f.text_field :price, class: "form-control" %><br/>
    </div>
    <div class="form-group">
      Quantity: <%= f.text_field :quantity, class: "form-control" %><br/>
    </div>
    <div class="form-group">
      Category:
      <%= f.select :category_id, Category.options_for_select, class: "form-control" %><br>
    </div>
    <div class="form-group">
      Description: <%= f.text_area :description, class: "form-control" %><br/>
    </div>
    <div class="form-group">
      Image: <%= f.text_field :image, class: "form-control" %><br/>
    </div>
    <div class="form-group">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/categories/show.html.erb
<div class="block-product">
  <div class="block-category">
    <h3>Category</h3>
    <div class="list-category">
      <% @categories.map do |cate| %>
        <ul>
          <li><%= link_to cate.name, category_path(cate.id) %></li>
        </ul>
      <% end %>
    </div>
  </div>

  <div class="container" id="content">
    <h3>Sản phẩm mới</h3>
    <div class="row">
      <% @products.map do |product| %>
        <div class="col-lg-3 col-sm-6 mgt-20">
          <div class="col-inner" id="navproduct">
            <ul class="products">
              <li>
                <a href="#" class="product_link">
                  <img width="240" height="258" src="https://www.viettropfruit.com/wp-content/uploads/2016/08/nho-den-khong-hat-my-300x300.png" style="padding-right: 17px;">
                  <h8><%= product.name %></h8>
                </a>
                <span><%= product.price %>đ/kg</span>
                <a href="#" class="icon">
                  <i class="fa-solid fa-cart-shopping"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="block-product">
  <div class="block-category">
    <h3>Category</h3>
    <div class="list-category">
      <% @categories.map do |cate| %>
        <ul>
          <li><a href="#"><%= link_to cate.name, category_path(cate.id) %></a></li>
        </ul>
      <% end %>
    </div>
  </div>

  <div class="container" id="content">
    <h3>Sản phẩm mới</h3>
    <div class="row">
      <div class="col-lg-3 col-sm-6 mgt-20">
        <div class="col-inner" id="navproduct">
          <ul class="products">
            <li>
              <a href="#" class="product_link">
                <img width="240" height="258" src="https://www.viettropfruit.com/wp-content/uploads/2016/08/nho-den-khong-hat-my-300x300.png" style="padding-right: 17px;">
                <h8>Nho đen không hạt</h8>
              </a>
              <span>250.000đ/kg</span>
              <a href="#" class="icon">
                <i class="fa-solid fa-cart-shopping"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-sm-6 mgt-20">
        <div class="col-inner" id="navproduct">
          <ul class="products">
            <li>
              <a href="#" class="product_link">
                <img width="240" height="258" src="https://www.viettropfruit.com/wp-content/uploads/2016/08/nho-do-ba-moi-phan-rang-300x300.png" style="padding-right: 17px;">
                <h8>Nho đỏ Phan Răng</h8>
              </a>
              <span>60.000đ/kg</span>
              <a href="#" class="icon">
                <i class="fa-solid fa-cart-shopping"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-sm-6 mgt-20">
        <div class="col-inner" id="navproduct">
          <ul class="products">
            <li>
              <a href="#" class="product_link">
                <img width="240" height="258" src="https://www.viettropfruit.com/wp-content/uploads/2016/09/dua-luoi-taki-nhat-ban-300x300.png" style="padding-right: 17px;">
                <h8>Dừa lưới taki Nhập Bản</h8>
              </a>
              <span>85.000đ/kg</span>
              <a href="#" class="icon">
                <i class="fa-solid fa-cart-shopping"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-sm-6 mgt-20">
        <div class="col-inner" id="navproduct">
          <ul class="products">
            <li>
              <a href="#" class="product_link">
                <img width="240" height="258" src="https://www.viettropfruit.com/wp-content/uploads/2016/09/tao-xanh-ninh-thuan-300x300.png" style="padding-right: 17px;">
                <h8>Táo xanh Ninh Thuận</h8>
              </a>
              <span>50.000đ/kg</span>
              <a href="#" class="icon">
                <i class="fa-solid fa-cart-shopping"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-sm-6 mgt-20">
        <div class="col-inner" id="navproduct">
          <ul class="products">
            <li>
              <a href="#" class="product_link">
                <img width="240" height="258" src="https://www.viettropfruit.com/wp-content/uploads/2016/08/nho-den-khong-hat-my-300x300.png" style="padding-right: 17px;">
                <h8>Nho đen không hạt</h8>
              </a>
              <span>250.000đ/kg</span>
              <a href="#" class="icon">
                <i class="fa-solid fa-cart-shopping"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-sm-6 mgt-20">
        <div class="col-inner" id="navproduct">
          <ul class="products">
            <li>
              <a href="#" class="product_link">
                <img width="240" height="258" src="https://www.viettropfruit.com/wp-content/uploads/2016/08/nho-do-ba-moi-phan-rang-300x300.png" style="padding-right: 17px;">
                <h8>Nho đỏ Phan Răng</h8>
              </a>
              <span>60.000đ/kg</span>
              <a href="#" class="icon">
                <i class="fa-solid fa-cart-shopping"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-sm-6 mgt-20">
        <div class="col-inner" id="navproduct">
          <ul class="products">
            <li>
              <a href="#" class="product_link">
                <img width="240" height="258" src="https://www.viettropfruit.com/wp-content/uploads/2016/09/dua-luoi-taki-nhat-ban-300x300.png" style="padding-right: 17px;">
                <h8>Dừa lưới taki Nhập Bản</h8>
              </a>
              <span>85.000đ/kg</span>
              <a href="#" class="icon">
                <i class="fa-solid fa-cart-shopping"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-sm-6 mgt-20">
        <div class="col-inner" id="navproduct">
          <ul class="products">
            <li>
              <a href="#" class="product_link">
                <img width="240" height="258" src="https://www.viettropfruit.com/wp-content/uploads/2016/09/tao-xanh-ninh-thuan-300x300.png" style="padding-right: 17px;">
                <h8>Táo xanh Ninh Thuận</h8>
              </a>
              <span>50.000đ/kg</span>
              <a href="#" class="icon">
                <i class="fa-solid fa-cart-shopping"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_bander.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" style="height: 600px;">
    <div class="carousel-item active">
      <img class="d-block w-100" src="http://www.hoaquasach.vn/wp-content/uploads/2017/03/1-0x0.jpg" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://y5kbp0ifnvobj.vcdn.cloud/uploads/filecloud/2022/April/29/12131-940441651198508-1651198508.jpg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://y5kbp0ifnvobj.vcdn.cloud/uploads/filecloud/2019/November/6/4312-673831573020630-1573020630.png" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<div class="footer">
		<div class="container" id="footer">
			<div class="row">
	    	<div class="col-lg-3 col-sm-6">
	    		<div class="col-inner">
	    			<h6><%= t ".purchase" %></h6>
			    	<ul>
			    		<li><%= t ".text_footer" %></li>
			    		<li><%= t ".text_footer1" %></li>
			    		<li><%= t ".text_footer2" %></li>
			    		<li><%= t ".text_footer3" %></li>
		    		</ul>
	    		</div>
	    	</div>
	    	<div class="col-lg-3 col-sm-6">
	    		<div class="col-inner">
	    			<h6><%= t ".promotion" %></h6>
		    		<ul>
		    			<li>Hot Deal</li>
		    			<li>Voucher</li>
		    			<li>Discount</li>
		    		</ul>
	    		</div>
	    	</div>
	    	<div class="col-lg-3 col-sm-6">
	    		<div class="col-inner">
	    			<h6><%= t ".text_footer4" %></h6>
		    		<ul>
		    			<li><%= t ".text_footer5" %></li>
		    			<li><%= t ".text_footer6" %></li>
		    			<li><%= t ".text_footer7" %></li>
		    		</ul>
	    		</div>
	    	</div>
	    	<div class="col-lg-3 col-sm-6">
	    		<div class="col-inner">
	    			<h6><%= t ".text_footer8" %></h6>
		    		<ul>
		    			<li>Facebook</li>
		    			<li><%= t ".telephone" %></li>
		    			<li><%= t ".address" %></li>
		    		</ul>
	    		</div>
	    	</div>
	    </div>
    </div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="navbar navbar-expand-lg navbar-light bg-dark navbar-dark">
		<div class="header">
			<%= link_to "Green Fruit", root_path, id: "logo" %>
			<div class="form-inline my-2 my-lg-0">
				<% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.fullname %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="dropdown-item"><%= link_to "Profile", current_user %></li>
              <li class="dropdown-item"><%= link_to "Settings", '#' %></li>
              <% if current_user.admin? %>
          			<li class="dropdown-item"><%= link_to "Magener", admin_root_path %></li>
          		<% end %>
              <li class="divider"></li>
              <li class="dropdown-item">
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <button class="btn btn-outline-info my-2 my-sm-0" type="submit">
	      	<%= link_to t(".text_header"), login_path %>
	      	</button>
	      	<button class="btn btn-outline-info my-2 my-sm-0" type="submit"><%= link_to t(".sign_up"), signup_path %></button>
        <% end %>
	      <button class="btn btn-outline-info my-2 my-sm-0" type="submit"><%= t ".text_header1" %> | 
	      	<i class="fa-solid fa-cart-shopping"></i></button>
	    </div>
    </div>
	</div>

	<div class="navbar navbar-expand-lg navbar-light bg-dark navbar-dark">
	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="#"><%= t ".home" %><span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item active">
	        <a class="nav-link" href="#"><%= t ".shop" %></a>
	      </li>
	      <li class="nav-item active dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          <%= t ".product" %>
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	          <a class="dropdown-item" href="#"><%= t ".meat" %></a>
	          <a class="dropdown-item" href="#"><%= t ".fish" %></a>
	          <a class="dropdown-item" href="#"><%= t ".fruit" %></a>
	          <div class="dropdown-divider"></div>
	          <a class="dropdown-item" href="#"><%= t ".green" %></a>
	        </div>
	      </li>
	      <li class="nav-item active">
	        <a class="nav-link disabled" href="#"><%= t ".text_header2" %></a>
	      </li>
	      <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
            Language <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li class="dropdown-item"><%= link_to "English", locale: "en" %></li>
            <li class="dropdown-item"><%= link_to "Vietnamese", locale: "vi" %></li>
          </ul>
        </li>
	    </ul>
	    <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= t ".search" %></button>
	    </form>
	  </div>
	</div>
</header>

app/views/layouts/_sidebar_admin.html.erb
<nav id="sidebar">
    <div class="sidebar-header">
        <h3>Bootstrap Sidebar</h3>
    </div>

    <ul class="list-unstyled components">
        <p>Dummy Heading</p>
        <li class="active">
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                    <a href="#">Home 1</a>
                </li>
                <li>
                    <a href="#">Home 2</a>
                </li>
                <li>
                    <a href="#">Home 3</a>
                </li>
            </ul>
        </li>
        <li>
            <%= link_to "Categories", admin_categories_path %>
        </li>
        <li>
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
                <li>
                    <a href="#">Page 1</a>
                </li>
                <li>
                    <a href="#">Page 2</a>
                </li>
                <li>
                    <a href="#">Page 3</a>
                </li>
            </ul>
        </li>
        <li>
            <%= link_to "Products", admin_products_path %>
        </li>
        <li>
            <a href="#">Contact</a>
        </li>
    </ul>

    <ul class="list-unstyled CTAs">
        <li>
            <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
        </li>
        <li>
            <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
        </li>
    </ul>
</nav>
  

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CayGreenFruit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div class="wrapper">
      <%= render "layouts/sidebar_admin" %>
      <div id="content">
          <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CayGreenFruit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row" style="justify-content: center;">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <div class="form-group">
      <%= f.label :fullname %>
      <%= f.text_field :fullname, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Createnew", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.fullname %>
      </h1>
      <h1>
        <%= @user.email %>
      </h1>
    </section>
  </aside>
</div>